config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "photos#index"
  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file, PhotoUploader
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
     def index
        @photos = Photo.order(created_at: :desc)
     end

     def new
        @photo=Photo.new
     end

  def create
     @photo = current_user.photos.new(photo_params)
    if @photo.save
      redirect_to photo_path(@photo)
      else
      render:new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end
  def destroy
        @photo = Photo.find(params[:id])
        @photo.destroy

        redirect_to photos_path
   end


  private
  def photo_params
    params.require(:photo).permit(:file, :caption)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instaclone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "InstaClone", photos_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "About", photos_path %></li>
            <li><%= link_to "New Photo", new_photo_path %></li>
          </ul>
          <% if user_signed_in? %>
      <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
      <li><%= link_to "#{current_user.email}, logout?", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
    <% end %>
        </div>
      </div>
    </nav>

      <section class="container">
            <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
          <% end %>

          <%= yield %>
      </section>
</body>
</html>

app/views/photos/index.html.erb
<% if @photos.any? %>
      <div class="row">
        <% @photos.in_groups_of(3) do |group| %>
          <% group.compact.each do |photo| %>
          <div class="col-md-4">
            <div class="photo">


              <div class="photo-head">
                <h4 class="name">
                  <%= photo.user ? photo.user.email : "RG Kuching" %>
                  <%= photo %>
                </h4>
              </div>
              
              <div class="image center-block">
                <%= link_to photo_path(photo) do %>
                  <%= image_tag(photo.file_url, class: "img-responsive") if photo.file.present? %>
                <% end %>
              </div>
              <p class="caption">
                <%= photo.caption %>
                <%= link_to photo_path(photo), method: :delete, data: { confirm: "Are you sure you want to delete this photo?" }, class: "btn btn-danger btn-xs pull-right" do %>
                  <i class="i fa fa-trash"></i>
                <% end %>
              </p>
            </div>
          </div>
          <% end %>
        <% end  %>
      </div>
    <% else  %>
      <p>No photos found.</p>
    <% end %>

app/views/photos/new.html.erb
<div class="form-wrapper">
      <%= form_for @photo, html: { class: 'form-horizontal', multipart: true } do |f| %>

        <div class="form-group">
          <%= f.label :file %><br>
          <%= f.file_field :file, class: "form-control" %>
        </div>

        <div class="form-group text-center">
          <%= f.label :caption %><br>
          <%= f.text_field :caption, class: "form-control" %>
        </div>

        <div class="form-group text-center">
          <%= f.submit class: "btn btn-success btn-block" %>
        </div>
      <% end %>
    </div>

app/views/photos/show.html.erb
  <div class="row">
      <div class="col-md-12 col-md-offset-0v text-center">
        <%= image_tag(@photo.file_url) if @photo.file.present? %>
        <h3><%= @photo.caption %></h1>
        <h4><%= @photo ? @photo : "RG Kuching" %></h4>
      </div>
    </div>